const configuration = {
  CASH_IN_COMISSION_FEE: 0.03,
  CASH_IN_MAX_AMOUNT: 5.00,
  CASH_OUT_NATURAL_COMISSION_FEE: 0.3,
  CASH_OUT_NATURAL_WEEK_LIMIT: 1000.00,
  CASH_OUT_LEGEL_COMISSION_FEE: 0.3,
  CASH_OUT_MIN_LEGEL_AMOUNT: 0.50,
};

module.exports = configuration;
